### ISSUE TITLE
General To-Do

### ISSUE THREAD

**Issue by arthurcast** [arthurcast/MealGenerator#1]
### User Stories

- [ ]  User can click a button that will get a random meal from an external API (see below)
 - [ ] The app should display: **Recipe name, Ingredients, Instructions** and a **Picture** of the meal
 - [ ] By clicking the button again, another meal will be generated

# Bonus Features

- [ ] The app should display a **YouTube Video**
